Update get-secretmanager-secrets.yml

diff --git a/.github/workflows/get-secretmanager-secrets.yml b/.github/workflows/get-secretmanager-secrets.yml
--- a/.github/workflows/get-secretmanager-secrets.yml
+++ b/.github/workflows/get-secretmanager-secrets.yml
@@ -3,10 +3,37 @@ on:
   workflow_dispatch:
 
 jobs:
-    secret:
-        runs-on: ubuntu-latest
-        steps:  
-            - name: get-secret
-              uses: step-security/get-secretmanager-secrets@main
-              with:
-                secrets: password
+  access-secrets-main:
+    permissions:
+      contents: 'read'
+      id-token: 'write'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Harden the runner (Audit all outbound calls)
+        uses: step-security/harden-runner@rc
+        with:
+          egress-policy: audit
+
+      - uses: actions/checkout@v6
+
+      - name: Authenticate to Google Cloud (with @main)
+        id: "auth"
+        uses: step-security/google-github-auth@main
+        with:
+            service_account: "test-account@arc-gke-demo2.iam.gserviceaccount.com"
+            workload_identity_provider: "projects/786066019368/locations/global/workloadIdentityPools/github-pool/providers/github"
+
+      - name: Get secrets
+        id: "secret"
+        uses: step-security/get-secretmanager-secrets@main
+        with: 
+            secrets: token:arc-gke-demo2/test
+
+      - name: Check token output
+        run: |
+          if [ "${{ steps.secret.outputs.token }}" != "integration-test" ]; then
+            echo "Error: Token output does not equal 'integration-test'"
+            echo "Actual value: ${{ steps.secret.outputs.token }}"
+            exit 1
+          fi
+          echo "Success: Token output equals 'integration-test'"
